package com.gcrth.chatroom.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.gcrth.chatroom.entity.Massage;

import com.gcrth.chatroom.dao.MassageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig massageDaoConfig;

    private final MassageDao massageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        massageDaoConfig = daoConfigMap.get(MassageDao.class).clone();
        massageDaoConfig.initIdentityScope(type);

        massageDao = new MassageDao(massageDaoConfig, this);

        registerDao(Massage.class, massageDao);
    }
    
    public void clear() {
        massageDaoConfig.clearIdentityScope();
    }

    public MassageDao getMassageDao() {
        return massageDao;
    }

}
